import "./globals.css";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "./components/Footer";
import About from "./about/page";
import Tips from "./tips/page";
import Faqs from "./components/Faqs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add the font weights you need
  variable: "--font-poppins", // Create a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased flex flex-col min-h-screen`}>
        
        {/* ✅ Navbar is Sticky & Always Visible, but has its Own Space */}
        <div className="sticky top-0 left-0 w-full z-50 bg-white shadow-md">
          <Navbar />
        </div>

        {/* ✅ Content Starts Below the Navbar */}
        <main className="flex-1">
          {children}
          <About />
          <Tips/>
          <Faqs/>
        </main>

        {/* ✅ Footer Always at the Bottom */}
        <Footer />
        
      </body>
    </html>
  );
}
